# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :repo => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.15.137',
    :disks => {
        :sata1 => {
            :dfile => home + '/VirtualBox VMs/sata1.vdi',
            :size => 10240,
            :port => 1
        }
    }
  }
}

Vagrant.configure("2") do |config|

    config.vm.box_version = "1804.02"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
    
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            #yum -y install epel-release
            rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum -y install createrepo rpm-build rpmdevtools yum-utils autoconf automake gcc gcc-c++ less libpcap libpcap-devel libtool lksctp-tools lksctp-tools-devel ncurses ncurses-devel openssl openssl-devel gsl gsl-devel autoconf-archive gmock-devel gtest-devel gtest nginx
            cd /root/
            yumdownloader --enablerepo=epel --source sipp 
            useradd mockbuild
            rpm -i sipp-3.5.1-1.el7.src.rpm
            yum-builddep rpmbuild/SPECS/sipp.spec -y
            rpmbuild -bb rpmbuild/SPECS/sipp.spec
            mkdir /usr/share/nginx/html/repo
            cp /root/rpmbuild/RPMS/x86_64/sipp-3.5.1-1.el7.centos.x86_64.rpm /usr/share/nginx/html/repo/
            createrepo /usr/share/nginx/html/repo/
            sed -i "48i\\        autoindex on;"  /etc/nginx/nginx.conf
            echo "[local-repo]" >> /etc/yum.repos.d/local.repo
            echo "name=otus-local-repo" >> /etc/yum.repos.d/local.repo
            echo "baseurl=http://localhost/repo" >> /etc/yum.repos.d/local.repo
            echo "gpgcheck=0" >> /etc/yum.repos.d/local.repo
            echo "enabled=1" >> /etc/yum.repos.d/local.repo
            systemctl start nginx
            systemctl enable nginx
          SHELL
  
        end
    end
  end